# Generated by Django 5.2.3 on 2025-06-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_student_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='uuid',
        ),
    ]
